static-dir:     "_env:STATIC_DIR:static"
host:           "0.0.0.0" # any IPv4 host
port:           3000
approot:        "http://0.0.0.0:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"
copyright: Insert copyright statement here
